In [8]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Amount": np.random.randint(10, 5000, 1000),
    "Class": ['A']*990 + ['B']*10
})

df

     Amount Class
0      4975     A
1      4173     A
2      1165     A
3      4858     A
4      2539     A
..      ...   ...
995    3076     B
996    1428     B
997     418     B
998    1773     B
999    4151     B

[1000 rows x 2 columns]

In [9]:
# Here this is called as imbalanced dataset 
# where 99% data is saying there is A class , therefore ML model cannot predict correctly
df['Class'].value_counts()

Class
A    990
B     10
Name: count, dtype: int64

In [11]:
# so we need to take only 10 class A rows for ML model
A = df[df['Class'] == 'A']
B = df[df['Class'] == 'B']
print(A.shape, B.shape)

(990, 2) (10, 2)

In [12]:
A_sample = A.sample(n=10)
A_sample.shape

(10, 2)

In [15]:
new_df = pd.concat([A_sample, B])
new_df

     Amount Class
894    2738     A
39       63     A
93     2558     A
53     4714     A
619    2826     A
859    4417     A
655    2474     A
100    2571     A
782    4033     A
163    1933     A
990    2651     B
991    3759     B
992    2627     B
993    4354     B
994    3657     B
995    3076     B
996    1428     B
997     418     B
998    1773     B
999    4151     B

In [18]:
new_df['Class'].value_counts()
# now this data is ready for ML

Class
A    10
B    10
Name: count, dtype: int64